Attempt to fix AttributeError which causes fatal exception (program crash).
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "/root/idb-backend/idigbio_ingestion/tropicos-mediaing.py", line 90, in get_media_wrapper
    url, connectione.exceptions.errno, connectione.exceptions.message)
AttributeError: 'ConnectionError' object has no attribute 'exceptions'
<Greenlet at 0x3a6ecd0: get_media_wrapper((u'http://www.tropicos.org/ImageDownload.aspx?imag)> failed with AttributeError

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/root/idb-backend/idigbio_ingestion/tropicos-mediaing.py", line 106, in <module>
    mediaing.main(TROPICOS_URLFILTER)
  File "/root/idb-backend/idigbio_ingestion/mediaing.py", line 373, in main
    get_media_consumer(urlfilter)
  File "/root/idb-backend/idigbio_ingestion/mediaing.py", line 359, in get_media_consumer
    for r in p.imap_unordered(get_media_wrapper, urls):
  File "/usr/local/lib/python2.7/dist-packages/gevent/pool.py", line 102, in next
    raise value.exc
AttributeError: 'ConnectionError' object has no attribute 'exceptions'