update elasticseach package to version 5 to match ES version
According to notes on PyPi:

  For Elasticsearch 5.0 and later, use the major version 5 (5.x.y) of the library.

Hoping the newer library will help the ConnectionError:

```
ConnectionError: ConnectionError(('Connection aborted.', BadStatusLine("''",))) caused by: ProtocolError(('Connection aborted.', BadStatusLine("''",)))
```