convert boto md5 bytes to string for comparison
key.md5 returns a bytes object, not a string.  This leads to a mismatch when bytes are compared
to a str.

  boto.exception.S3DataError: BotoClientError:
    MD5 of downloaded did not match given MD5: b'bac1d6137adc8974f200173b6a4f05b8' vs. bac1d6137adc8974f200173b6a4f05b8

This seems to be caused by an interaction between 'boto' and 'six'.

We are already using the latest version of these libraries.